name: CICD pipeline

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      # - name: Create .env file
      #   run: echo "MONGO_PASSWORD=${{ secrets.MONGO_PASSWORD }}" >> .env
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin ${{ secrets.DOCKER_PASSWORD }} 
      - name: Build docker image
        run: docker build -t iamzion/shoe-store . 
      - name: Publish image to docker hub
        run: docker push iamzion/shoe-store

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to AWS EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Docker pull & build
        script: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} ---password-stdin ${{ secrets.DOCKER_PASSWORD }}
          docker pull iamzion/shoe-store
          docker image rm -f iamzion/shoe-store
          docker-compose -f docker_service_setup/docker-compose.shoe_store.yaml up -d